let state={project:null,timeline:null,selected:null};
const $=s=>document.querySelector(s);
const log=(m,o)=>{$('#log').textContent=`${new Date().toLocaleTimeString()}  ${m}${o?'\n'+JSON.stringify(o,null,2):''}\n\n`+$('#log').textContent};
const fmt=s=>{s=Number(s||0);const m=Math.floor(s/60),r=(s%60).toFixed(1).padStart(4,'0');return `${m}:${r}`};
async function api(url,opts={}){const r=await fetch(url,opts);if(!r.ok){let t=await r.text();throw new Error(`${r.status} ${t}`)}const ct=r.headers.get('content-type')||'';return ct.includes('application/json')?r.json():r.text()}

async function loadProjects(){const projects=await api('/api/projects');const sel=$('#projectSelect');sel.innerHTML='';projects.forEach(p=>{const o=document.createElement('option');o.value=p.name;o.textContent=p.name+(p.has_manifest?'':' (needs plan)');sel.appendChild(o)});if(!projects.length){log('No projects found. Create one with storyforge init.');return}if(!state.project||!projects.some(p=>p.name===state.project))state.project=projects.find(p=>p.has_manifest)?.name||projects[0].name;sel.value=state.project;await loadTimeline()}

async function loadTimeline(){if(!state.project)return;try{state.timeline=await api(`/api/projects/${encodeURIComponent(state.project)}/timeline`);renderAll();log(`Loaded ${state.project}`)}catch(e){log('Could not load timeline: '+e.message);state.timeline=null;renderAll()}}

function renderAll(){const t=state.timeline;$('#projectName').textContent=t?.title||state.project||'—';$('#duration').textContent=t?fmt(t.duration):'—';$('#sceneCount').textContent=t?.scenes?.length??'—';$('#cost').textContent=t?`$${Number(t.budget.estimated_usd||0).toFixed(2)}`:'—';$('#budget').textContent=t?`$${Number(t.budget.budget_limit_usd||0).toFixed(2)}`:'—';$('#narration').src=t?.narration_url||'';renderRuler();renderTimeline();renderFilmstrip();renderInspector()}

function routeLabel(s){return s.route_override||s.decision?.route||'AUTO'}
function statusSymbol(s){if(s.generated_exists)return '▶';if(s.keyframe_exists&&routeLabel(s)==='FLOW_SUBSCRIPTION')return '◆';if(s.keyframe_exists)return '◐';return '○'}

function renderRuler(){const r=$('#ruler');r.innerHTML='';const d=state.timeline?.duration||0;if(!d)return;const step=d>600?60:d>180?30:d>60?10:5;for(let x=0;x<=d;x+=step){const el=document.createElement('div');el.className='tick';el.style.left=`${(x/d)*100}%`;el.textContent=fmt(x);r.appendChild(el)}}

function renderTimeline(){const el=$('#timeline');el.innerHTML='';const t=state.timeline;if(!t)return;const total=Math.max(1,t.duration);t.scenes.forEach(s=>{const c=document.createElement('div');c.className='scene-tile'+(state.selected===s.id?' selected':'');c.style.width=`${Math.max(130,Math.min(360,(s.duration/total)*1800))}px`;const media=s.keyframe_url?`<img src="${s.keyframe_url}?v=${Date.now()}"/>`:`<span>${statusSymbol(s)} Add image</span>`;c.innerHTML=`<div class="tile-image">${media}</div><div class="tile-body"><div class="tile-head"><strong>Scene ${String(s.id).padStart(3,'0')}</strong><span>${fmt(s.duration)}</span></div><div class="tile-text">${escapeHtml(s.text||'')}</div><div class="route">${statusSymbol(s)} ${routeLabel(s)}</div></div>`;c.onclick=()=>selectScene(s.id);el.appendChild(c)})}

function renderFilmstrip(){const el=$('#filmstrip');el.innerHTML='';const t=state.timeline;if(!t)return;t.scenes.forEach(s=>{const c=document.createElement('div');c.className='film-card'+(state.selected===s.id?' selected':'');c.innerHTML=s.keyframe_url?`<img src="${s.keyframe_url}?v=${Date.now()}"/>`:`<div class="fallback">${statusSymbol(s)} No guide image</div>`;const m=document.createElement('div');m.className='film-meta';m.innerHTML=`<strong>Scene ${s.id}</strong> · ${fmt(s.duration)}<br><span class="${s.generated_exists?'status-ready':'status-warn'}">${routeLabel(s)}</span>`;c.appendChild(m);c.onclick=()=>selectScene(s.id);el.appendChild(c)})}

function selectScene(id){state.selected=id;renderTimeline();renderFilmstrip();renderInspector();const s=currentScene();if(s&&$('#narration').src){$('#narration').currentTime=s.start||0}}
function currentScene(){return state.timeline?.scenes?.find(s=>s.id===state.selected)}

function renderInspector(){const s=currentScene();$('#inspectorEmpty').hidden=!!s;$('#inspectorForm').hidden=!s;if(!s){$('#videoPreview').hidden=true;$('#imagePreview').hidden=true;$('#emptyPreview').hidden=false;return}$('#sceneTitle').textContent=`Scene ${String(s.id).padStart(3,'0')}`;$('#sceneTime').textContent=`${fmt(s.start)} → ${fmt(s.end)}`;$('#sceneText').value=s.text||'';$('#importance').value=s.importance??0.5;$('#importanceValue').textContent=Number(s.importance??0.5).toFixed(2);$('#complexity').value=s.motion_complexity||s.decision?.motion_complexity||1;const ro=$('#routeOverride');ro.innerHTML='<option value="AUTO">AUTO</option>';state.timeline.routes.forEach(r=>{const o=document.createElement('option');o.value=r;o.textContent=r;ro.appendChild(o)});ro.value=s.route_override||'AUTO';$('#prompt').value=s.prompt||'';$('#sceneStatus').textContent=`Director: ${s.decision?.route||'—'} · ${s.decision?.reason||''}`;if(s.generated_url){$('#videoPreview').src=s.generated_url;$('#videoPreview').hidden=false;$('#imagePreview').hidden=true;$('#emptyPreview').hidden=true}else if(s.keyframe_url){$('#imagePreview').src=s.keyframe_url+'?v='+Date.now();$('#imagePreview').hidden=false;$('#videoPreview').hidden=true;$('#emptyPreview').hidden=true}else{$('#videoPreview').hidden=true;$('#imagePreview').hidden=true;$('#emptyPreview').hidden=false;$('#emptyPreview').textContent='No image or video for this scene'}}

async function saveScene(){const s=currentScene();if(!s)return;const body={text:$('#sceneText').value,importance:Number($('#importance').value),motion_complexity:Number($('#complexity').value),route_override:$('#routeOverride').value};state.timeline=await api(`/api/projects/${encodeURIComponent(state.project)}/scenes/${s.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});renderAll();log(`Saved scene ${s.id}`)}
async function savePrompt(){const s=currentScene();if(!s)return;await api(`/api/projects/${encodeURIComponent(state.project)}/scenes/${s.id}/prompt`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:$('#prompt').value})});s.prompt=$('#prompt').value;log(`Saved prompt for scene ${s.id}`)}
async function upload(kind,input){const s=currentScene();if(!s||!input.files[0])return;const fd=new FormData();fd.append('file',input.files[0]);state.timeline=await api(`/api/projects/${encodeURIComponent(state.project)}/scenes/${s.id}/${kind}`,{method:'POST',body:fd});renderAll();log(`${kind} uploaded for scene ${s.id}`);input.value=''}
async function flowPacket(){const s=currentScene();if(!s)return;const r=await api(`/api/projects/${encodeURIComponent(state.project)}/scenes/${s.id}/flow-packet`,{method:'POST'});log(`Flow packet created for scene ${s.id}`,r)}
async function validate(){if(!state.project)return;const r=await api(`/api/projects/${encodeURIComponent(state.project)}/inspect`);const b=$('#validationBadge');b.textContent=r.valid?'Valid':`${r.errors.length} error(s)`;b.className='pill '+(r.valid?'good':'bad');log('Validation',r)}
async function director(){if(!state.project)return;const r=await api(`/api/projects/${encodeURIComponent(state.project)}/director`,{method:'POST'});log('Director plan updated',r.estimate);await loadTimeline()}
async function renderProject(){if(!state.project)return;if(!confirm('Render the current project now?'))return;log('Render started…');try{const r=await api(`/api/projects/${encodeURIComponent(state.project)}/render`,{method:'POST'});log('Render complete',r)}catch(e){log('Render failed: '+e.message)}}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

$('#projectSelect').addEventListener('change',async e=>{state.project=e.target.value;state.selected=null;await loadTimeline()});$('#refreshBtn').onclick=loadTimeline;$('#validateBtn').onclick=validate;$('#directorBtn').onclick=director;$('#renderBtn').onclick=renderProject;$('#saveSceneBtn').onclick=saveScene;$('#savePromptBtn').onclick=savePrompt;$('#flowPacketBtn').onclick=flowPacket;$('#keyframeUpload').addEventListener('change',e=>upload('keyframe',e.target));$('#generatedUpload').addEventListener('change',e=>upload('generated',e.target));$('#importance').addEventListener('input',e=>$('#importanceValue').textContent=Number(e.target.value).toFixed(2));
loadProjects().catch(e=>log(e.message));
